//1 	target name that you want to create
NAME = libft.a
// 2	dependencies of the target
// 2.1 	files to be compiled + linked --> make target
SRCS = ft_atoi.c 
OBJS = $(SRCS:.c=.o)
// 3	commands to be executed
// 3.1	compiler command
CC = gcc
// 3.2	flags or options
CFLAGS = -Wall -Wextra -Werror .

// Repeat steps 1-3 for each target


// Makefile: 
//  automates the build process for the library. 
// The Makefile 
// instructions for compiling the source files into object files, 
// and then linking the object files into the final library.